version: '3'
services:
  app:
    build: .
    ports:
      - 3000:3000
      - 8000:8000
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    stdin_open: true
    tty: true
    command: /bin/sh
volumes:
  node_modules:
